require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.4
  NewCops: enable

  Exclude:
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/use_github_gem_spec.rb'
